/**
 * Do share the code to others but do not copy it.
 * @author ClaushCrz
 * @version 1.0.0
 */
package MiniLibrary;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class MainWindow1 extends javax.swing.JFrame {

    public MainWindow1() {
        initComponents();
    }

    static String file_path;
    FileManagement f_m = new FileManagement();
    ArrayList<ArrayList<String>> formatted_data = new ArrayList();
    CSVTest dataFormatter = new CSVTest();
    DefaultTableModel model = new DefaultTableModel();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = CreateTable();
        jLabel1 = new javax.swing.JLabel();
        AddDonationButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        donatorName = new javax.swing.JTextField();
        bookName = new javax.swing.JTextField();
        donatorGender = new javax.swing.JComboBox();
        SaveButton = new javax.swing.JButton();
        LoadButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mini Library v1.0.0");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Table.setModel(model);
        Table.setMaximumSize(new java.awt.Dimension(0, 0));
        jScrollPane1.setViewportView(Table);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Mini Library System");

        AddDonationButton.setText("Add Donation");
        AddDonationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDonationButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Donator Name");

        jLabel3.setText("Donator Gender");

        jLabel4.setText("Book Name");

        donatorName.setToolTipText("Insert donator's name.");

        bookName.setToolTipText("Insert the title of the book.");

        donatorGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "male", "female" }));

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        LoadButton.setText("Load");
        LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(donatorName)
                            .addComponent(bookName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(donatorGender, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(83, 83, 83))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddDonationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SaveButton)
                        .addGap(27, 27, 27)
                        .addComponent(LoadButton)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(donatorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(donatorGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddDonationButton)
                    .addComponent(SaveButton)
                    .addComponent(LoadButton))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayData(ArrayList<ArrayList<String>> data)
    {
        DefaultTableModel tmodel = (DefaultTableModel) Table.getModel();
        
        if (tmodel.getRowCount() > 0)
        {
            for (int i = tmodel.getRowCount() -1 ; i > -1; i--)
            {
                tmodel.removeRow(i);
            }
        }
        
        for (ArrayList<String> i : data)
        {
            tmodel.addRow(new Object[] 
            {
                i.get(0),
                i.get(1),
                i.get(2)
            });
        }
    }
    
    private void AddDataToTable(ArrayList<String> data)
    {
        DefaultTableModel tmodel = (DefaultTableModel) Table.getModel();
        tmodel.addRow(new Object[]{
            data.get(0),
            data.get(1),
            data.get(2)
        });
    }
    
    private JTable CreateTable()
    {
        model.addColumn("Donator Name");
        model.addColumn("Donator Gender");
        model.addColumn("Book Name");
        
        return new JTable(model);
    }
    
    private void LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadButtonActionPerformed
        file_path = f_m.GetFileAddress();
        String unformatted_data = "";
        try {
            unformatted_data = f_m.GetData(file_path);
            JOptionPane.showMessageDialog(this,"Load Successfully");

        } catch (IOException ex) {
            Logger.getLogger(MainWindow1.class.getName()).log(Level.SEVERE, null, ex);
        }
        formatted_data = dataFormatter.CSV_Derived(unformatted_data);
        
        DisplayData(formatted_data);
    }//GEN-LAST:event_LoadButtonActionPerformed

    private void AddDonationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDonationButtonActionPerformed
        String name = donatorName.getText();
        String gender = (String)donatorGender.getSelectedItem();
        String book_name = bookName.getText();
        
        ArrayList<String> data_placeholder = new ArrayList();
        data_placeholder.add(name);
        data_placeholder.add(gender);
        data_placeholder.add(book_name);
        formatted_data.add(data_placeholder);
        
        AddDataToTable(data_placeholder);
    }//GEN-LAST:event_AddDonationButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        file_path = f_m.GetFileAddress();
        try {
            f_m.Store_Data(file_path, formatted_data);
            if (file_path.equalsIgnoreCase("null"))
            {
                JOptionPane.showMessageDialog(this,"Saved Failed");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Saved Successfully");
            }
        } catch (IOException ex) {
            Logger.getLogger(MainWindow1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDonationButton;
    private javax.swing.JButton LoadButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTable Table;
    private javax.swing.JTextField bookName;
    private javax.swing.JComboBox donatorGender;
    private javax.swing.JTextField donatorName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
